home/urls.py
from django.urls import path
from .views.home_view import home,home_details
from .views.about_views import aboutUs
from .views.donate_views import donate
from .views.blog_views import blog_details,blogs
from .views.partner_views import partnerForm,partnership
from .views.fun_raising_views import funRaising
from .views.volunteer import volunteer
from .views.library_views import community_library,gallery
from .views.book_talk_views import bookTalk





app_name = 'home'
urlpatterns = [
    path('',home,name='home'),
    # path('work/<int:id>/', home_details, name='work_details'),
    path('about',aboutUs,name='about'),
    path('donate',donate,name='donate'),
    path('blog',blogs,name='blog'),
    # path('partnership',partnership,name='partnership'),
    # path('partnerForm',partnerForm,name='partnerForm'),
    path('blog/<int:blog_id>/', blog_details, name='blog-details'),
    path('volunteer',volunteer,name="volunteer"),
    path('gallery',gallery,name='gallery'),
    path('community_library',community_library,name='community_library'),
    path('book_talk',bookTalk,name='book_talk')
]

 

lgf_web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'))
]
if settings.DEBUG:
  urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views/about_views.py
from django.shortcuts import  render
from django.core.mail import send_mail
from django.conf import settings

from home.models import ContactFormSubmission,Team,Testimonial,BoardMembers



# CONTACT US FORM
def aboutUs(request):
    success_message = None
    teams = Team.objects.all()
    testimonial = Testimonial.objects.all()
    board_members = BoardMembers.objects.all()

    if request.method == 'POST':
        full_name = request.POST['full_name']
        email = request.POST['email']
        phone = request.POST['phone']
        message = request.POST['message']

        submission = ContactFormSubmission(
            full_name=full_name,
            email=email,
            phone=phone,
            message=message,
        )
        submission.save()

        # Send email
        try:
            send_mail(
                subject='Thank You for Contacting Us',
                message='Thank you for contacting us. We will get back to you soon!',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[email],  # Send thank-you email to the user
                fail_silently=False,
            )
            success_message = "Your message has been sent successfully!"
        except Exception as e:
            success_message = None

    return render(request, 'pages/about.html', {'success_message': success_message,'teams': teams,'testimonials':testimonial,'board_members':board_members})

home/views/blog_views.py
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render,redirect
from django.core.mail import send_mail
from django.conf import settings
from home.models import Blog,Comment
from django.contrib import messages
from home.form import CommentForm





# BLOG HERE
def blogs(request):
    all_blogs = Blog.objects.all()
    paginator = Paginator(all_blogs, 4)
    page_number = request.GET.get('page')
    blogs = paginator.get_page(page_number)
    
    
    context = {
        'blogs': blogs,
    }


    return render(request,'pages/blog.html',context)






def blog_details(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comments = Comment.objects.filter(blog=blog)
    
    comment_count = comments.count()
    
    

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.save()
            
            full_name = form.cleaned_data['full_name'],
            
            send_mail(
                subject = 'New Blog Comment',
                message = f"New Comment from {full_name}:\n\n",
                from_email=settings.EMAIL_HOST_USER,
                recipient_list = ['skyhightech93@gmail.com'],
                fail_silently=False,
            )
            
            print("email sent")
            return redirect('home:blog-details', blog_id=blog.id)

    else:
        form = CommentForm() 

    return render(request, 'pages/single.html', {'blog': blog, 'comments': comments,'comment_count': comment_count,'form': form})

home/views/book_talk_views.py
from django.shortcuts import get_object_or_404, render,redirect


def bookTalk(request):
    
    
    return render(request,'pages/book_talk.html')

home/views/donate_views.py
from django.http import HttpResponse
from django.shortcuts import  render,redirect
from django.core.mail import send_mail
from django.conf import settings
import paypalrestsdk
from home.models import Donation

paypalrestsdk.configure({
    "mode": "live",  
    "client_id": 'AWWbypiy6yDnYIlWs1E9Lao8rUR3k1yVgkLb3azj9IPJ2L9mRKs_kGehErA3rEpsSasRQLFm8YLXeG24',
    "client_secret": 'EDR2ox3hcvyu1qksrW_GdWGYsZz8HqUKbZ0Mg_YocW2r2HNvARu_dcaobvDlgilm7oL7SZIaf2O0Oscn',
})

def donate(request):
    if request.method == 'POST':
        
        name = request.POST.get('full_name')
        email = request.POST.get('email')
        amount = request.POST.get('amount')
        custom_amount = request.POST.get('customAmount')

        if amount:
            print(f"Amount: {amount}")
            total_amount = float(amount)
        elif custom_amount:
            print(f"Custom Amount: {custom_amount}")
            total_amount = float(custom_amount)
        else:
            return HttpResponse("Please provide a donation amount")

        # Create a PayPal payment object
        payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "paypal",
            },
            "transactions": [
                {
                    "amount": {
                        "total": str(total_amount),
                        "currency": "USD",
                    },
                    "description": f"Donation from {name}",
                }
            ],
            "redirect_urls": {
                "return_url": "http://127.0.0.1:8000/donation/success/",
                "cancel_url": "http://127.0.0.1:8000/donation/cancel/",
            }
        })

        # Create the payment on PayPal
        if payment.create():
            donation = Donation(name=name, email=email, amount=total_amount)
            donation.save()
            message = f"A donation has been made through the website"
            message = f"Full Name: {name}\n"
            message += f"Email: {email}\n"
            message += f"Amount: {total_amount}\n"
            message += f"Message: {message}\n"
            send_mail(
                subject = 'Donation Made',
                message = message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list = ['Learnersgirlsfoundation@gmail.com'],
                fail_silently=False,
            )
    
            send_mail(
                subject = 'Thank You for Your Donation',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list = [email],
                fail_silently=False,
                        message = f'''
Dear {name},

Thank you for your generous donation to Leaner's Girls Foundation. Your support is greatly appreciated and makes a significant difference in our mission.

Your contribution will help us [mention how the donation will be used, e.g., support a specific cause, project, or program]. We are truly grateful for your generosity and commitment to our cause.

We value your support and look forward to keeping you updated on how your donation is making an impact. If you have any questions or would like to learn more about our work, please feel free to contact us.

Once again, thank you for your kindness and support. Together, we can make a positive change in the lives of those we serve.

Sincerely,
Founder : Kumuriwor Alira Bushiratu
 Leaner's Girls Foundation
'''
            )
            
            for link in payment.links:
                if link.method == "REDIRECT":
                    return redirect(link.href)
        else:
            return HttpResponse(f"Payment creation failed: {payment.error}")


    
    return render(request,'pages/donate.html') 

home/views/fun_raising_views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from home.models import Fundraiser  # Import the Fundraiser model you defined
from django.contrib import messages

def funRaising(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        country = request.POST.get('country')
        area_of_interest = request.POST.get('areaOfInterest')
        summary = request.POST.get('summary_of_proposed_partnership')
        start_date = request.POST.get('start_date')
        finish_date = request.POST.get('finish_date')
        fundraising_amount = request.POST.get('fundraisingAmount')

        # Create a new Fundraiser object and save it to the database
        fundraiser = Fundraiser(
            email=email,
            firstname=firstname,
            lastname=lastname,
            country=country,
            area_of_interest=area_of_interest,
            summary_of_proposed_partnership=summary,
            start_date=start_date,
            finish_date=finish_date,
            fundraising_amount=fundraising_amount
        )
        fundraiser.save()

        # Send an email to the fundraiser
        subject = 'Thank You for Your Fundraising Efforts'
        message = f'Dear {firstname} {lastname},\n\n' \
                  'Thank you for your fundraising efforts. We appreciate your support!\n\n' \
                  'Sincerely,\n' \
                  'Your Organization Name'
        from_email = 'your@email.com'  # Replace with your organization's email
        recipient_list = [email]
        send_mail(subject, message, from_email, recipient_list, fail_silently=False)

        # Show a success message
        return render(request, 'pages/partnerforms.html', {'success_message': 'Form submitted successfully.'})


    return render(request, 'pages/fun_raising.html')

home/views/home_view.py
from django.shortcuts import redirect, render,get_object_or_404
from home.models import OurWork,Metrics
from django.shortcuts import  render
from django.core.mail import send_mail
from django.conf import settings
from home.models import ContactFormSubmission,Blog,Donation,Team,Testimonial,Cause
from django.core.mail import send_mail
from django.conf import settings
from django.db.models.functions import Random
import paypalrestsdk
from django.http import HttpResponse


paypalrestsdk.configure({
    "mode": "live",  
    "client_id": 'AWWbypiy6yDnYIlWs1E9Lao8rUR3k1yVgkLb3azj9IPJ2L9mRKs_kGehErA3rEpsSasRQLFm8YLXeG24',
    "client_secret": 'EDR2ox3hcvyu1qksrW_GdWGYsZz8HqUKbZ0Mg_YocW2r2HNvARu_dcaobvDlgilm7oL7SZIaf2O0Oscn',
})

def home(request):
    works = OurWork.objects.all()
    team_members = Team.objects.all()
    statistics = Metrics.objects.first()
    testimonials = Testimonial.objects.all()
    causes = Cause.objects.all()
    success_message = None  # Initialize success_message
    
    # DISPLAY RANDOM BLOGS HERE
    random_blogs = Blog.objects.annotate(random_order=Random()).order_by('random_order')[:3]

    
    
    if request.method == 'POST':
        
        if 'contact_submit' in request.POST:
            full_name = request.POST.get('full_name')
            email = request.POST.get('email')
            phone = request.POST.get('phone')
            message = request.POST.get('message')

            submission = ContactFormSubmission(
            full_name=full_name,
            email=email,
            phone=phone,
            message=message,
            )
            submission.save()

            # Send email
            try:
                send_mail(
                subject='Thank You for Contacting Us',
                message='Thank you for contacting us. We will get back to you soon!',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[email],  # Send thank-you email to the user
                fail_silently=False,
            )
                success_message = "Your message has been sent successfully!"
            except Exception as e:
                success_message = None
                
        
        if 'donation_submit' in request.POST:
            if request.method == 'POST':
                name = request.POST.get('full_name')
                email = request.POST.get('email')
                amount = request.POST.get('amount')
                custom_amount = request.POST.get('customAmount')
            if amount:
                print(f"Amount: {amount}")
                total_amount = float(amount)
            elif custom_amount:
                print(f"Custom Amount: {custom_amount}")
                total_amount = float(custom_amount)
            else:
                return HttpResponse("Please provide a donation amount")
        
        
            payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "paypal",
            },
            "transactions": [
                {
                    "amount": {
                        "total": str(total_amount),
                        "currency": "USD",
                    },
                    "description": f"Donation from {name}",
                }
            ],
            "redirect_urls": {
                "return_url": "http://127.0.0.1:8000/donation/success/",
                "cancel_url": "http://127.0.0.1:8000/donation/cancel/",
            }
            })

        # Create the payment on PayPal
            if payment.create():
                donation = Donation(name=name, email=email, amount=total_amount)
                donation.save()
                message = f"A donation has been made through the website"
                message = f"Full Name: {name}\n"
                message += f"Email: {email}\n"
                message += f"Amount: {total_amount}\n"
           
                send_mail(
                subject = 'Donation Made',
                message = message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list = ['Learnersgirlsfoundation@gmail.com'],
                fail_silently=False,
                )
    
                send_mail(
                subject = 'Thank You for Your Donation',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list = [email],
                fail_silently=False,
                        message = f'''
Dear {name},

Thank you for your generous donation to Leaner's Girls Foundation. Your support is greatly appreciated and makes a significant difference in our mission.

Your contribution will help us [mention how the donation will be used, e.g., support a specific cause, project, or program]. We are truly grateful for your generosity and commitment to our cause.

We value your support and look forward to keeping you updated on how your donation is making an impact. If you have any questions or would like to learn more about our work, please feel free to contact us.

Once again, thank you for your kindness and support. Together, we can make a positive change in the lives of those we serve.

Sincerely,
Founder : Kumuriwor Alira Bushiratu
 Leaner's Girls Foundation
'''
            )
            
                for link in payment.links:
                    if link.method == "REDIRECT":
                        return redirect(link.href)
            else:
                return HttpResponse(f"Payment creation failed: {payment.error}")
        
    
    

    
    return render(request, 'pages/index.html', {'works': works, 'statistics': statistics, 'success_message': success_message,'random_blogs': random_blogs,'team_members': team_members, 'testimonials': testimonials, 'causes': causes,})



def home_details(request, id):
    works = get_object_or_404(OurWork, pk=id)
    return render(request, 'pages/work_details.html', {'works': works})

home/views/library_views.py
from django.shortcuts import render
from home.models import LibraryPictures  # Import your LibraryPicture model

def community_library(request):
    

    return render(request, 'pages/library.html')





def gallery(request):
    
    # Get all LibraryPicture objects from the database
    pictures = LibraryPictures.objects.all()
    return render(request,'pages/gallery.html',{'gallery':pictures})

home/templates/shared/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learner Girl Foundation - {% block title %} {% endblock %}</title>
        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.2/components/teams/team-1/assets/css/team-1.css">
        <!-- Template Stylesheet -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        </head>
  <body>
    <!-- Navbar -->
      
    {% include 'shared/navbar.html' %}

     {% block carousel %}
  <!-- Carousel Start -->
    <div class="carousel">
        <div class="container-fluid">
            <div class="owl-carousel">
                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{% static 'img/DSC_6951.jpg' %}" alt="Image">
                    </div>
                    <div class="carousel-text">
                        <h1>Empowering Tomorrow's Leaders</h1>
                        <p>
                        Unlocking the hidden potential within each and every girl, one at a time, through education, mentorship, and empowerment
                        programs that build strong foundations for future leaders and change-makers.
                        </p>
                        <div class="carousel-btn">
                            <a class="btn btn-custom" href="{% url 'home:donate' %}">Donate Now</a>
                            <a class="btn btn-custom btn-play" data-toggle="modal"
                                data-src="https://www.youtube.com/embed/DWRcNpR6Kdc" data-target="#videoModal">Watch
                                Video</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{% static 'img/LGF-125.jpg' %}" alt="Image">
                    </div>
                    <div class="carousel-text">
                        <h1>Bridging the Educational Divide</h1>
                        <p>
                            Our commitment to education knows no boundaries. We tirelessly strive to ensure that quality education is accessible to
                            every child, regardless of their geographic location or socioeconomic background, as we believe that education is the
                            key to bridging divides and fostering a brighter future
                        </p>
                        <div class="carousel-btn">
                            <a  class="btn btn-custom" href="{% url 'home:volunteer' %}">Volunteer</a>
                            <a class="btn btn-custom btn-play" data-toggle="modal"
                                data-src="https://www.youtube.com/embed/DWRcNpR6Kdc" data-target="#videoModal">Watch
                                Video</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{% static 'img/event-2.jpg' %}" alt="Image">
                    </div>
                    <div class="carousel-text">
                        <h1>Books, Bytes, and Bright Futures</h1>
                        <p>
                          At Learners Girls' Foundation, we are on a mission to promote literacy, digital skills, and gender equality. Through the
                          power of books and technology, we aim to empower young minds, equipping them with the knowledge and skills needed to
                          create brighter and more equitable futures
                        </p>
                        <div class="carousel-btn">
                            <a class="btn btn-custom" href="{% url 'home:donate' %}">Donate Now</a>
                            <a class="btn btn-custom btn-play" data-toggle="modal"
                                data-src="https://www.youtube.com/embed/DWRcNpR6Kdc" data-target="#videoModal">Watch
                                Video</a>
                        </div>
                    </div>
                </div>


                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{% static 'img/WhatsApp Image 2023-09-23 at 6.52.24 AM (2).jpeg' %}" alt="Image">
                    </div>
                    <div class="carousel-text">
                        <h1>Community, Education, Empowerment</h1>
                        <p>
                          Learners Girls' Foundation is dedicated to nurturing positive change within our communities through the transformative
                          power of education and empowerment. Together, we are building a brighter, more inclusive world where every girl has the
                          opportunity to thrive and succeed, regardless of the challenges they face
                        </p>
                        <div class="carousel-btn">
                            <a class="btn btn-custom" href="{% url 'home:donate' %}">Donate Now</a>
                            <a class="btn btn-custom btn-play" data-toggle="modal" data-src="https://www.youtube.com/embed/DWRcNpR6Kdc"
                                data-target="#videoModal">Watch
                                Video</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel End -->

     {% endblock %}


      {% block content %}

      {% endblock %}


  </body>
      <!-- Bootstrap Js -->
   <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
        <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
        <script src="{% static 'lib/parallax/parallax.min.js' %}"></script>
        
        <!-- Contact Javascript File -->
        <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
        <script src="{% static 'mail/contact.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
</html>

home/templates/shared/footer.html
{% load static %}
  <!-- Footer Start -->
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <div class="footer-contact">
            <h2>Our Head Office</h2>
            <p><i class="fa fa-map-marker-alt"></i>XVGV+28, Paga, Ghana</p>
            <p><i class="fa fa-phone-alt"></i>+233 24 295 0362</p>
            <p><i class="fa fa-envelope"></i>Learnersgirlsfoundation@gmail.com</p>
            <div class="footer-social">
              <!-- <a class="btn btn-custom" href=""><i class="fab fa-twitter"></i></a>
              <a class="btn btn-custom" href=""><i class="fab fa-facebook-f"></i></a>
              <a class="btn btn-custom" href=""><i class="fab fa-youtube"></i></a> -->
              <!-- <a class="btn btn-custom" href=""><i class="fab fa-instagram"></i></a> -->
              <a class="btn btn-custom" target="_blank" href="https://www.linkedin.com/company/learners-girls-foundation/"><i class="fab fa-linkedin-in"></i></a>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-link">
            <h2>Popular Links</h2>
            <a href="">About Us</a>
            <a href="">Contact Us</a>
            <a href="">Volunteer</a>
            <a href="">Donate</a>
            <a href="">Latest Blog</a>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-link">
            <h2>Useful Links</h2>
            <a href="{% url 'home:gallery' %}">Gallery</a>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-newsletter">
            <h2>Newsletter</h2>
            <form>
              <input class="form-control" placeholder="Email goes here">
              <button class="btn btn-custom">Submit</button>
              <label>Don't worry, we don't spam!</label>
            </form>
          </div>
        </div>
      </div>
    </div>
    
  </div>
  <!-- Footer End -->

home/templates/shared/navbar.html
{% load static %}

<!-- Navigation Bar -->


        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                 <a class="navbar-brand" href="/">
                 <img src="{% static 'img/logo__.png' %}" alt="Learners Girls Foundation" class="d-inline-block align-top rounded-circle">
                
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <a href="/" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'home:about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'home:donate' %}" class="nav-item nav-link">Donate</a>
                        <a href="{% url 'home:blog' %}" class="nav-item nav-link">Blog</a>
                        <a href="{% url 'home:volunteer' %}" class="nav-item nav-link">Join us</a>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- Nav Bar End -->   

home/templates/shared/top_nav.html
{% load static %}


     <!-- Top Bar Start -->
        <div class="top-bar d-none d-md-block">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8">
                        <div class="top-bar-left">
                            <div class="text">
                                <i class="fa fa-phone-alt"></i>
                                <p>+123 456 7890</p>
                            </div>
                            <div class="text">
                                <i class="fa fa-envelope"></i>
                                <p>info@example.com</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="top-bar-right">
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar End -->